import React from 'react'

import Head from 'next/head'
import Image from 'next/image'

import About from '../components/sectionAbout/about'
import Start from '../components/sectionStart/start'
import Advantages from '../components/sectionAdvantages/advantages'
import Upper from '../components/upperScreen/upper'
import Partners from '../components/sectionPartners/partners'
import Teachers from '../components/sectionTeachers/teachers'
import Footer from '../components/footer/footer'

import s from '../styles/Home.module.scss'


export default function Home() {
  return (
    <>
      <Head>
        <title>Первый курс</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Upper />

      <main className={s['main']}>
        <About />

        <Start />

        <Advantages />

        <Partners />

        {/* <section className={s['section-program'] + ' section main-container'}>
          <div className={s['section-program__title-container']}>
            <div className={s['section-title-icon'] + ' ' + s['section-program__icon']}></div>
            <h2 className={s['section-title'] + ' ' + s['section-program__title-upper']}>
              Программа обучения
            </h2>
            <p className={s['section-program__desc-title'] + ' desc'}>
              Больше 90% учеников прошли полный курс и смогли собрать свой первый компьютер
            </p>
          </div>
        </section> */}

        <Teachers />
      </main>

      <Footer />
    </>
  )
}
